# Generated by Django 6.0.4 on 2026-04-16 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('organization_id', models.CharField(default='ORG001', max_length=50)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('department', models.CharField(default='', max_length=100)),
                ('role', models.CharField(default='', max_length=100)),
                ('professional_email', models.EmailField(default='no-reply@company.com', max_length=254)),
                ('job_title', models.CharField(default='', max_length=100)),
                ('office_location', models.CharField(default='', max_length=100)),
                ('employment_type', models.CharField(default='FULL_TIME', max_length=50)),
                ('probation_start_date', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('work_status', models.CharField(default='ACTIVE', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(default='', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(default='', max_length=10)),
                ('marital_status', models.CharField(default='', max_length=50)),
                ('nationality', models.CharField(default='', max_length=50)),
                ('profile_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('personal_email', models.EmailField(default='', max_length=254)),
                ('address', models.TextField(default='')),
                ('postal_code', models.CharField(default='', max_length=20)),
                ('country', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('district_county', models.CharField(default='', max_length=50)),
                ('emergency_contact_name', models.CharField(default='', max_length=100)),
                ('emergency_contact_number', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rules', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=100)),
                ('document_id', models.CharField(max_length=50, unique=True)),
                ('file_path', models.CharField(max_length=255)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr_engine.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days', models.FloatField()),
                ('leave_type', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_history', to='hr_engine.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_balances', models.JSONField(default=dict)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='hr_engine.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('earnings', models.JSONField(default=dict)),
                ('deductions', models.JSONField(default=dict)),
                ('net_salary', models.FloatField()),
                ('lwp_days', models.FloatField(default=0)),
                ('base_daily_rate', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_salaries', to='hr_engine.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.FloatField()),
                ('bonus', models.FloatField(default=0)),
                ('allowances', models.JSONField(default=dict)),
                ('deductions', models.JSONField(default=dict)),
                ('pay_cycle', models.CharField(default='MONTHLY', max_length=50)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='hr_engine.employee')),
            ],
        ),
    ]
