# Generated by Django 6.0.4 on 2026-04-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ALLUS CORP', max_length=100)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('theme_color', models.CharField(default='#4338ca', max_length=20)),
                ('custom_html', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
