# Generated by Django 6.0.4 on 2026-04-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_engine', '0002_companybranding'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(default='MANDATORY', max_length=50)),
            ],
        ),
    ]
