# Generated by Django 6.0.4 on 2026-04-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_engine', '0003_companyholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavehistory',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
